# frozen_string_literal: true

# Auto-include InquiryAttrs::Concern into every ActiveRecord model so that
# the .inquirer macro is available without an explicit include in each class.
#
# Generated by: rails inquiry_attrs:install
#
# To opt out of auto-include, remove this file and add
#   include InquiryAttrs::Concern
# to whichever models need it.
ActiveSupport.on_load(:active_record) do
  include InquiryAttrs::Concern
end
