# frozen_string_literal: true

# Auto-include StatesmanScaffold::Concern into every ActiveRecord model
# so that the `with_state_machine` class macro is available application-wide.
#
# Generated by: rails statesman_scaffold:install
require "statesman"

Statesman.configure { storage_adapter(Statesman::Adapters::ActiveRecord) }

ActiveSupport.on_load(:active_record) do
  include StatesmanScaffold::Concern
end
